# Generated by Django 3.1 on 2021-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(max_length=10),
        ),
    ]
